### ISSUE TITLE
Set up solar without solar on a leg

### ISSUE THREAD

**Issue by kneath** [SpanPanel/Span#10]
First off — thanks for this integration! It's been my favorite of the new house. 

I've finally gotten my solar & electrical contractors to get my SolarEdge inverters sending data to my Span panels, unfortunately I can't for the life of me figure out how to get that data back into my HA install. In the README you have:

> Look in your Span app for "solar" if any and identify the individual circuit(s).

But I have no solar circuits. Setting the config to 0 for the legs reports no data. I've even looked through every single sensor reporting in HA and none of them map to the current solar generation. But I can see the solar & battery info in Span. Is this something not available in their API? Or am I missing something?

![IMG_7532](https://github.com/user-attachments/assets/8796f153-9715-4622-8721-47d44523007d)

**Comment by cayossarian** [comment]
@kneath, look in Circuits/In Panel and you should see the circuits for Solar.  Usually these are 30 and 32 in the US where two 120v out-of-phase circuits make 240v.

![image](https://github.com/user-attachments/assets/d9b0e6db-b09c-4dce-9c1e-83ccab26e229)

**Comment by kneath** [comment]
Interesting — yeah I don't have that (that was where I looked first). I've gone through all 64 circuits (two panels) and nothing with solar in it.
![IMG_7533](https://github.com/user-attachments/assets/8e2558b7-76e4-4126-8336-f9d6db9aa072)
![IMG_7534](https://github.com/user-attachments/assets/7913c316-56a4-4809-93ba-b4d67eab5148)

**Comment by cayossarian** [comment]
A lot depends on how the installer set it up and how the SPAN panel is labeled.  I see you have a downstream load panel which I don't.  Since the app understands you have solar generation it is getting this information from somewhere so maybe call SPAN support or the installer and ask them which legs they used for solar.  Putting zero's in one or more of the solar configuration effectively turns those sensors off in the integration which is useful if you only have one circuit feeding power like in the UK.  

I only included these solar sensors because some of us have inverters that don't integrate with SPAN other than through the legs like you saw in mine.  If you have an inverter that is supported natively by HA you could instead use that data.

**Comment by kneath** [comment]
Oh man, my world if Span would talk to me directly. I'll try and dig in and see where I get. One of my initial motives for getting this information from Span is that Span requires a direct Ethernet connection between my inverters and the panels, but that Ethernet connection is also the only networking interface that the inverters support their modbus API through (that I could otherwise hook into home assistant).

**Comment by mbbush** [comment]
> Oh man, my world if Span would talk to me directly.

Unfortunately this feature isn't going to work for your setup. The span panel's local api only reports the data that it measures itself, not the data that it receives from external devices like your solaredge inverter. 

Due to an unrelated quirk of the data model, the list of circuits (that includes circuit names) doesn't include circuits configured as having a direct connection to a solar inverter. However, the panel status endpoint still reports the power flows of those circuits (it reports all measured power flows by the space number in the panel, regardless of configuration). This integration has a workaround for allowing the user to designate particular space number(s) as solar, and then using the values reported in the panel status endpoint as your solar measurement.

If the power from your solar panels flows to your solaredge battery/gateway/hub first, and then only later into the span panel, then the only way the span panel knows your solar production is by querying your inverter over the modbus API. This data is not currently exposed in the span panel local api. I wish it were! 

The best I can offer you is an unofficial, untested, unsupported suggestion that if you were to put an ethernet switch between your span panel and inverter, not connected to your home network, and added a raspberry pi or similar client to that network, which had a second network interface connected to your home network, then the raspberry pi would _probably_ be able to talk to the solaredge inverter, and the span integration would _probably_ still Just Work.

**Comment by kneath** [comment]
@mbbush Thank you so much! You described my setup exactly. Your suggestion was my next guess, and resembles a similar solution I had for a previous solar install. I'll see if I can get that setup working. Appreciate the info — I'm happy to close this issue. Maybe some slight improvements to the README are in order, but otherwise nothing to do here.
